version: 0.2

env:
  variables:
    root_dir: 'webapp'
    build_artifacts_dir: 'dist'

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing source NPM dependencies...
      - cd $root_dir
      - npm install
      # - echo Download .env.production from s3://$bucket/env/
      # - aws s3 cp s3://$bucket/env/.env.production .
  build:
    commands:
      - echo Build started on `date`
      - echo "Webhook was triggerd by ${CODEBUILD_WEBHOOK_TRIGGER}"
      - sh ./scripts/build.sh --mode ${env}
  post_build:
    commands:
      - sh ./scripts/deploy.sh
